$color = rgba(21,37,40, 1.0)
$inner_color = rgba(21,37,40, 0.8)
$outer_color = rgba(230,234,234, 1.0)
$font_color = rgba(230,234,234, 1.0)
$check_color = rgba(90,147,170, 1.0)

image {
    monitor =
    path = ~/.config/omarchy/current/theme/unlock.png
    size = 250
    rounding = 0
    border_size = 0

    position = 0, 200
    halign = center
    valign = center
}
